name: Release Asset

on:
    release:
        types: [ created ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Compile
              run: php -d phar.readonly=0 compile-phar.php

            - name: Upload
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ github.event.release.upload_url }}
                asset_path: ./exercise-cleaner.phar
                #asset_name: exercise-cleaner
                asset_content_type: application/octet-stream
